### ISSUE TITLE
no --help 

### ISSUE THREAD

**Issue by msmeissn** [stealth/opmsg#14]
You seem to have dropped the --help option to opmsg ?

**Comment by stealth** [comment]
Its by intention. help is printed each time an argument is wrong. Since there is no --help,
opmsg --help would print the help screen :)

**Comment by msmeissn** [comment]
problem is during build of the package. help2man does not work...

reason is that if the configuration file is not present, it will only print WARN and ERR on the missing configuration file, but not the help.

**Comment by stealth** [comment]
--help was added a while ago
