### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [stealth/opmsg#16]
Dear Sebastian,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by stealth** [comment]
In fact, I would. I dont have any windows+compiler, though. I can check if it would work
with cygwin and gcc. However, I am not sure the concept of home directories
exists on windows or if some cygwin and POSIX compliance packages suffice to make it work.

**Comment by sergeevabc** [comment]
Err… Hello? :)

**Comment by sergeevabc** [comment]
@stealth, did you get a chance to look into this more thoroughly?

**Comment by stealth** [comment]
Hi mate

Sorry, I didnt mean to ignore your issue, but I dont have windows machine or compiler
setups, so its still on-hold.

**Comment by jaromil** [comment]
I recommend trying with mingw using a gnu/linux distro, it may be pretty smooth.

**Comment by markuszeller** [comment]
I made it work on Windows 10 using LXSS Ubuntu Bash.

**Comment by stealth** [comment]
nice to hear. share the knowledge top the ppl :)

**Comment by markuszeller** [comment]
It works good, but I think it will be almost impossible with my friends without having a GUI for it... Maybe I'll do a screencast with the neccessary steps.
