### ISSUE TITLE
What is the license which applies to this repository?

### ISSUE THREAD

**Issue by ifraixedes** [stealth/opmsg#2]
Hi, 

I'm wondering what license applies to this repository. Is there any which I missed to see it?

Thanks.

**Comment by skj3gg** [comment]
This project is under the GNUv3 License. It can be found at the top of `opmsg.cc`

**Comment by skj3gg** [comment]
https://github.com/stealth/opmsg/commit/c1810f9751f9553e4489b489d42d0b8545d07068 adds a LICENSE file now as well.

**Comment by ifraixedes** [comment]
Great, very clear now with the LICENSE file.

Many thanks.
