### ISSUE TITLE
Show public key

### ISSUE THREAD

**Issue by Fastidious** [stealth/opmsg#24]
If I want to show a persona's public key again (it shows once at persona's generation), how do I go to do that? Thanks!

**Comment by stealth** [comment]
if you have the (full) id of the persona like 11223344..., its as easy as

cat ~/.opmsg/11223344.../*pub.pem

The 11223344... id again is the hash of the persona key, so

sha256sum ~/.opmsg/11223344.../*pub.pem

should exactly yield 11223344.... (if sha256 is your configured persona hash (default))

maybe I should add an switch for convenience. The key DB was designed to be easy managable
with standard tools, so to avoid overhead with opmsg cmdline switches.
