### ISSUE TITLE
Referance persona via name instead of hash

### ISSUE THREAD

**Issue by AlexHasNoFace** [stealth/opmsg#29]
I think that the program should accept either the hash of a persona or the name of a persona.

If I run `opmsg -S -P c2551a55974408cc -i foo -o foo.sig` then everything works just fine, but I need to copy and paste the persona hash manually.
I think it would be much more intuitive and convenient if I could run `opmsg -S -P alex -i foo -o foo.sig` (Assuming that the name of `c2551a55974408cc` is `alex`).

At the very least, it would be nice to have a more helpful error message than `ERROR: keystore::keystore::load: Invalid hex id.:File exists`.

**Comment by stealth** [comment]
Names are basically free text and can be ambigious. The only unique identifier is the persona ID,
so you have to use these to un-ambigiously crypt the messages. For listings, you may pass a name
as a substr match for easier listing.

**Comment by stealth** [comment]
The issue is not about security, more about safety and non-ambigiousness.

However, I implemented this and updated the docu with a 'Message Encryption' section which explains how
this works. I hope this gives a boost and now everyone starts using it! :D
