### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [stealth/opmsg#6]
I would like to point out that identifiers like "[`__keystore_h__`](https://github.com/stealth/opmsg/blob/8847568cb2e6e491d0a9b07d9d4d8a0c96a36724/keystore.h#L21)" and "[`__misc_h__`](https://github.com/stealth/opmsg/blob/674587f4c959376c517902b0cc752eec2ebda46d/misc.h#L21)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by stealth** [comment]
OK. will consider this

**Comment by elfring** [comment]
Should this issue be kept open until the affected identifiers will be renamed?

**Comment by stealth** [comment]
already fixed

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/stealth/opmsg/commit/b2815529128bba859ee578f936008beacdeef049 "Renaming of include guards").
