### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [stealth/opmsg#8]
Would you like to add more error handling for return values from functions like the following?
- [mkdir](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Make a directory.") ⇒ [main](https://github.com/stealth/opmsg/blob/674587f4c959376c517902b0cc752eec2ebda46d/opmsg.cc#L785)
- [write](http://pubs.opengroup.org/onlinepubs/9699919799/functions/write.html "Write on a file.") ⇒ [keystore::add_persona](https://github.com/stealth/opmsg/blob/9c1487d6a63f7e45886b12f185400574609880d3/keystore.cc#L370)

**Comment by stealth** [comment]
Will check. Some of them are intentional like existing directories are no failure

**Comment by stealth** [comment]
solved
