### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [stealth/opmsg#9]
[An extra null pointer check is not needed in a function](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like [the destructor for the class "persona"](https://github.com/stealth/opmsg/blob/c16b8b7a6f96a174779c0237d5a2dc6ee5e64be0/keystore.h#L198 "Destructor for persona").

**Comment by stealth** [comment]
Indeed. But thats not a bug/mistake. BTW, that might not even always be a NULL check in C++.
it may be overloaded operator for that class

Thanks for reviewing the code.

**Comment by elfring** [comment]
I find that an extra null pointer check directly before [a call of the corresponding delete operator](http://en.cppreference.com/w/cpp/language/delete "delete expression") is a programming mistake.
